### ISSUE TITLE
Suggestion to Merge PR for Enhanced Azure.Communication.Email v1.0.0 Support

### ISSUE THREAD

**Issue by Megasware128** [jcamp-code/FluentEmail#17]
Hello,

I would like to bring to your attention a pull request in the Eiromplays/FluentEmail repository (PR [#1](https://github.com/Eiromplays/FluentEmail/pull/1)), which refactors the AzureEmailSender to support the latest stable version of the Azure.Communication.Email package (v1.0.0). I believe integrating these changes into the jcamp-code/FluentEmail repository would not only enhance Azure integration but also improve the upgradability of the Azure.Communication.Email package.

Key Changes in the PR:

1. Removal of sender name from email send requests to align with Azure standards.
2. Transition of AzureEmailSender to a singleton registration for efficiency.
3. Update to the stable version of Azure.Communication.Email package, enhancing the stability and future-proofing the library.

Integrating this PR would ensure that the FluentEmail package remains compatible with the latest advancements in Azure email communication, providing a more robust and scalable solution for users.

I look forward to your evaluation and consideration of this integration.

**Comment by JohnCampionJr** [comment]
You know, I was just looking at this.  I saw the Azure sender was using an old package.   I will get this merged too.
