### ISSUE TITLE
Suggestion for Removal of Prerelease Status Following Azure Email Support PR Integration

### ISSUE THREAD

**Issue by Megasware128** [jcamp-code/FluentEmail#19]
I noticed that the recent PR for updating AzureEmailSender to support the Azure.Communication.Email package v1.0.0 has been successfully merged. In light of this, I'd like to suggest considering the removal of the 'prerelease' status from the FluentEmail Azure integration.

With the integration of the stable version of Azure's email package, it seems appropriate to update the project status to reflect its current stability and reliability. This would offer users and potential contributors a more accurate understanding of the project's maturity and readiness for production use.

Thank you for your continuous efforts in improving FluentEmail

**Comment by JohnCampionJr** [comment]
Definitely. Will update on next release

**Comment by Qualizorg** [comment]
Is there anything we can do to make this happen? 

Thanks!
