### ISSUE TITLE
[BUG] Email.AttachFromFilename does not dispose stream

### ISSUE THREAD

**Issue by asherber** [jcamp-code/FluentEmail#23]
It seems that GitHub won't let me fork this repo, because I already have a fork of lukencode/FluentEmail. But please take a look at https://github.com/lukencode/FluentEmail/pull/384 and implement that fix here -- disposing of the file stream after reading the file to attach.

**Comment by MarkMenchavez** [comment]
Do you know if anyone is working on this already? if not, I can work on it.

**Comment by asherber** [comment]
There's already a suggested fix [here](https://github.com/lukencode/FluentEmail/pull/384/files). I just can't fork this repo because I already have a fork of the source repo.

**Comment by JohnCampionJr** [comment]
Thanks! I'll review and get it in ASAP.   You should be able to fork into a differently named repo though.
